trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'ACR-AngularApp'
  dockerImageName: 'angularapp'

stages:
- stage: BuildAndDeploy
  displayName: 'Build, Push and Deploy Angular Application'

  jobs:
  - job: BuildAndDeploy
    displayName: 'Build Docker Image, Push to ACR and Deploy to k3s'

    steps:

    - task: Docker@2
      displayName: 'Build and Push Image to ACR'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(dockerImageName)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          latest

    - task: SSH@0
      displayName: 'Deploy Angular Application to k3s'
      inputs:
        sshEndpoint: 'K3s-VM'
        runOptions: 'commands'
        commands: |
          sudo kubectl rollout restart deployment/angular-app-deployment -n angular-app
          sudo kubectl rollout status deployment/angular-app-deployment -n angular-app --timeout=180s
        readyTimeout: '20000'